# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bctl < Formula
  desc "A polished CLI for Britive JIT access management"
  homepage "https://github.com/smichalabs/britivectl-releases"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/smichalabs/britivectl-releases/releases/download/v0.6.0/bctl_Darwin_amd64.tar.gz"
      sha256 "a3dd4302d3e05161292c1fb7b239cbe766bc64e730ad65492506e8b7f20c8738"

      define_method(:install) do
        bin.install "bctl"
        bash_completion.install "completions/bctl.bash" => "bctl"
        zsh_completion.install "completions/bctl.zsh" => "_bctl"
        fish_completion.install "completions/bctl.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/smichalabs/britivectl-releases/releases/download/v0.6.0/bctl_Darwin_arm64.tar.gz"
      sha256 "26a5e40b11a63329a4d07563091852c48f6b69b73c42f742f14d26514996219f"

      define_method(:install) do
        bin.install "bctl"
        bash_completion.install "completions/bctl.bash" => "bctl"
        zsh_completion.install "completions/bctl.zsh" => "_bctl"
        fish_completion.install "completions/bctl.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/smichalabs/britivectl-releases/releases/download/v0.6.0/bctl_Linux_amd64.tar.gz"
      sha256 "7905bcd0c9369c6f3c011132ef3af6df559d511146f064f2cc3795cc8fb2b9ed"
      define_method(:install) do
        bin.install "bctl"
        bash_completion.install "completions/bctl.bash" => "bctl"
        zsh_completion.install "completions/bctl.zsh" => "_bctl"
        fish_completion.install "completions/bctl.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/smichalabs/britivectl-releases/releases/download/v0.6.0/bctl_Linux_arm64.tar.gz"
      sha256 "d8dbe73df4dd8d9f9fd0afeb9f963e3ad065e2eff859ce9ecc74899b6e22a7b2"
      define_method(:install) do
        bin.install "bctl"
        bash_completion.install "completions/bctl.bash" => "bctl"
        zsh_completion.install "completions/bctl.zsh" => "_bctl"
        fish_completion.install "completions/bctl.fish"
      end
    end
  end

  test do
    system "#{bin}/bctl", "version"
  end
end
