# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bctl < Formula
  desc "A polished CLI for Britive JIT access management"
  homepage "https://github.com/smichalabs/britivectl-releases"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/smichalabs/britivectl-releases/releases/download/v0.5.0/bctl_Darwin_amd64.tar.gz"
      sha256 "10311964772b486682ee2da7ed51b6b81bb9750fd1a2010837b800e41ec1f4e0"

      define_method(:install) do
        bin.install "bctl"
        bash_completion.install "completions/bctl.bash" => "bctl"
        zsh_completion.install "completions/bctl.zsh" => "_bctl"
        fish_completion.install "completions/bctl.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/smichalabs/britivectl-releases/releases/download/v0.5.0/bctl_Darwin_arm64.tar.gz"
      sha256 "1c58a07b33872d8a5985201519a09484b6f2ee84a960ba108fa5f7003d973d14"

      define_method(:install) do
        bin.install "bctl"
        bash_completion.install "completions/bctl.bash" => "bctl"
        zsh_completion.install "completions/bctl.zsh" => "_bctl"
        fish_completion.install "completions/bctl.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/smichalabs/britivectl-releases/releases/download/v0.5.0/bctl_Linux_amd64.tar.gz"
      sha256 "412d3dc99b151151c5950a954742ba514fc32ac548d4f8bc83519108e1a283b8"
      define_method(:install) do
        bin.install "bctl"
        bash_completion.install "completions/bctl.bash" => "bctl"
        zsh_completion.install "completions/bctl.zsh" => "_bctl"
        fish_completion.install "completions/bctl.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/smichalabs/britivectl-releases/releases/download/v0.5.0/bctl_Linux_arm64.tar.gz"
      sha256 "09d626ce254d523e04a2ff892ad318a5936e67cc9569239e274de03c9075dda8"
      define_method(:install) do
        bin.install "bctl"
        bash_completion.install "completions/bctl.bash" => "bctl"
        zsh_completion.install "completions/bctl.zsh" => "_bctl"
        fish_completion.install "completions/bctl.fish"
      end
    end
  end

  test do
    system "#{bin}/bctl", "version"
  end
end
