# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bctl < Formula
  desc "A polished CLI for Britive JIT access management"
  homepage "https://github.com/smichalabs/britivectl-releases"
  version "0.11.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/smichalabs/britivectl-releases/releases/download/v0.11.0/bctl_Darwin_amd64.tar.gz"
      sha256 "175820ed49a4a76ec4b37c3470f975760cd69adba9d4034dfc5103c8edcf76b4"

      define_method(:install) do
        bin.install "bctl"
        bash_completion.install "completions/bctl.bash" => "bctl"
        zsh_completion.install "completions/bctl.zsh" => "_bctl"
        fish_completion.install "completions/bctl.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/smichalabs/britivectl-releases/releases/download/v0.11.0/bctl_Darwin_arm64.tar.gz"
      sha256 "13790a9ab442ee5af3a539a3d27139d2abc1754ab0bc7e740b3df2950722a6e7"

      define_method(:install) do
        bin.install "bctl"
        bash_completion.install "completions/bctl.bash" => "bctl"
        zsh_completion.install "completions/bctl.zsh" => "_bctl"
        fish_completion.install "completions/bctl.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/smichalabs/britivectl-releases/releases/download/v0.11.0/bctl_Linux_amd64.tar.gz"
      sha256 "d5e00897cc2bfce268edc35fe0a7219eeb11ad999aca24fdb07fe8389af571b3"
      define_method(:install) do
        bin.install "bctl"
        bash_completion.install "completions/bctl.bash" => "bctl"
        zsh_completion.install "completions/bctl.zsh" => "_bctl"
        fish_completion.install "completions/bctl.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/smichalabs/britivectl-releases/releases/download/v0.11.0/bctl_Linux_arm64.tar.gz"
      sha256 "6d31b4563d35c1167b6504db7aeaa461ca524e51b6622b6beb43a9e4ce909e15"
      define_method(:install) do
        bin.install "bctl"
        bash_completion.install "completions/bctl.bash" => "bctl"
        zsh_completion.install "completions/bctl.zsh" => "_bctl"
        fish_completion.install "completions/bctl.fish"
      end
    end
  end

  test do
    system "#{bin}/bctl", "version"
  end
end
